honeycombio/helm-charts

opentelemetry-collector/.helmignore
opentelemetry-collector/Chart.yaml
opentelemetry-collector/README.md
opentelemetry-collector/templates/NOTES.txt
opentelemetry-collector/templates/_helpers.tpl
opentelemetry-collector/templates/configmap.yaml
opentelemetry-collector/templates/deployment.yaml
opentelemetry-collector/templates/hpa.yaml
opentelemetry-collector/templates/secret.yaml
opentelemetry-collector/templates/service.yaml
opentelemetry-collector/values.yaml

chart to deploy the OpenTelemetry collector configured with recommended defaults and the Honeycomb exporter

OpenTelemetry Collector for Honeycomb

---

opentelemetry-collector/Chart.yaml
opentelemetry-collector/README.md
opentelemetry-collector/templates/configmap.yaml
opentelemetry-collector/values.yaml

Adds sample_rate to the collector configuration and bumps the release to the latest.

Add sample_rate and update version of otel collector

---

honeycomb/Chart.yaml
opentelemetry-collector/Chart.yaml
opentelemetry-collector/README.md
opentelemetry-collector/templates/configmap.yaml
opentelemetry-collector/values.yaml
secure-tenancy/Chart.yaml

- Updates image versions on each chart
- Adds support for the sample_rate_attribute config parameter on the otel collector

Update chart versions

---

honeycomb/README.md

Hard to know with YAML, but I _think_ this is a typo?

readme: fix typo

---

opentelemetry-collector/templates/deployment.yaml
opentelemetry-collector/templates/service.yaml
opentelemetry-collector/values.yaml

Creates a ports section / mappings to allow for each section to be toggle on/off, as well as the ports themselves to change. Modifies both the service and deployment

Create config options for ports in values file

---

charts/refinery/Chart.yaml

Updates refinery and chart version

[refinery] - upgrade to refinery 1.4

---

charts/refinery/Chart.yaml

Updates refinery version to 1.6.1 and chart version to 1.3.1

[refinery] upgrade to Refinery 1.6.1

---

charts/refinery/README.md

Adds docs on expected behaviours when updating refinery configuration and sampling rules.
- Linked #83 
- Updates README with expected behaviours when changing configuration and sampling rules

[refinery] Update docs on pod recycling for config changes

---

charts/refinery/CHANGELOG.md
charts/refinery/Chart.yaml

Refinery Chart changelog updated and chart version updated to v1.4.0

Prep refinery helm chart release v1.4.0

---

charts/honeycomb/README.md
charts/honeycomb/templates/daemonset.yaml
charts/honeycomb/values.yaml

applying additional labels on daemonset pod labels
More flexibility around labeling k8s resources
No breaking changes

[honeycomb] add pod labels

---

charts/refinery/CHANGELOG.md
charts/refinery/Chart.yaml

### Description
Prepares the Refinery v1.5.0 release.
- Adds changelog entry
- Updates chart version to 1.5.0

Prepare refinery v1.5.0 release

---

charts/honeycomb/CHANGELOG.md

[honeycomb] prepare 1.3.1 agent release

---

charts/honeycomb/Chart.yaml

forgot to update the chart version 😞

[honeycomb] prepare 1.3.1 agent release pt2

---

charts/secure-tenancy/CHANGELOG.md
charts/secure-tenancy/Chart.yaml

[secure-tenancy] prepare 1.1.0 release

---

charts/refinery/Chart.yaml
charts/refinery/sample-configs/config_complete.yaml
charts/refinery/values.yaml

The only user-facing enhancement is the new RedisUsername config value.

[refinery] bump app version to 1.10.0

---

charts/refinery/CHANGELOG.md
charts/refinery/Chart.yaml

[refinery] prepare 1.6.0 release

---

charts/refinery/CHANGELOG.md

[refinery] docs: fix typo in changelog

---

charts/refinery/CHANGELOG.md
charts/refinery/Chart.yaml

Prepeares thes Refinery v1.7.0 chart release.
- Adds changlog entry
- Updates chart version to 1.7.0

[refinery] Prepare v1.7.0 release

---

charts/honeycomb/CHANGELOG.md
charts/honeycomb/Chart.yaml

Prepares the v1.4.0 release.
- Update chart version to 1.4.0

[honeycomb] Prepare v1.4.0 release

---

charts/honeycomb/Chart.yaml

honeycomb-kubernetes-agent has been updated.

Update to latest agent

---

charts/honeycomb/CHANGELOG.md
charts/honeycomb/Chart.yaml

**Describe Changes**
1. Update `version` in the `Chart.yaml` file to 1.5.0
2. Update `CHANGELOG.md` to include details from updated agent

[honeycomb] prep honeycomb agent helm chart v1.5.0

---

charts/refinery/CHANGELOG.md
charts/refinery/Chart.yaml

**changes made**
- update changelog for refinery chart
- bump refinery chart version to v1.9.0

[refinery] prep refinery chart v1.9.0

---

charts/refinery/Chart.yaml
charts/refinery/sample-configs/rules_complete.yaml

Bump refinery version, as well as extend the demo yaml file

Bump refinery to 1.14.1

---

charts/refinery/Chart.yaml
charts/refinery/sample-configs/rules_complete.yaml

Bump Refinery version to [1.15.0](https://github.com/honeycombio/refinery/releases/tag/v1.15.0)
Adds scope-based rules

[refinery] bump app version to 1.15.0

---

charts/honeycomb/CHANGELOG.md
charts/honeycomb/Chart.yaml

Release prep for Honeycomb Kubernetes Agent helm chart v1.5.2

Prepare Honeycomb v1.5.2

---

charts/refinery/CHANGELOG.md
charts/refinery/Chart.yaml

Prepares the refinery v1.12.0 release.
- Updates chart version to v1.12.0

[refinery] Prepare v1.12.0 release

---

charts/opentelemetry-collector/CHANGELOG.md
charts/opentelemetry-collector/Chart.yaml

prep opentelemetry collector chart v1.2.1
- update chart version from 1.2.0 to 1.2.1

[opentelemetry-collector] prep otel collector chart v1.2.1

---

charts/refinery/CHANGELOG.md
charts/refinery/Chart.yaml

Refinery chart release 1.12.1
- Closes #171 
- Version bump
- Chaneglog update

[refinery] prep release 1.12.1

---

charts/refinery/sample-configs/config_complete.yaml

The new refinery added several configuration changes. This updates the sample to include them. 
I checked that it still parses correctly with 
`yj -yj <charts/refinery/sample-configs/config_complete.yaml | jq .`

Update sample config with new fields

---

charts/refinery/Chart.yaml

Bumps refinery version to the latest (1.16.0)

Bump refinery version to 1.16.0

---

charts/refinery/CHANGELOG.md
charts/refinery/Chart.yaml
charts/refinery/sample-configs/config_complete.yaml

Prep 1.13.0

---

charts/refinery/CHANGELOG.md
charts/refinery/Chart.yaml

[refinery] prepare 1.15.1 release

---

charts/honeycomb/Chart.yaml

update to latest [release](https://github.com/honeycombio/honeycomb-kubernetes-agent/releases/tag/v2.5.5)

[agent] update agent version to 2.5.5

---

charts/honeycomb/Chart.yaml

Updates agent version to latest
- Update agent version to 2.5.6

[agent] update agent version to 2.5.6

---

charts/honeycomb/CHANGELOG.md
charts/honeycomb/Chart.yaml

Prepares the 1.5.5 honeycomb kubernetes agent
- Update chart version to 1.5.5

[agent] Prepare v1.5.5 release

---

charts/honeycomb/CHANGELOG.md
charts/honeycomb/Chart.yaml

Prep k8s-1.6.0 release

---

.github/workflows/add-to-project-v2.yml

Point the workflow to the collections board

chore: update workflow to Collections

---

charts/refinery/CHANGELOG.md
charts/refinery/Chart.yaml
charts/refinery/README.md

prepare refinery 1.17.0 release.

chore: prep refinery 1.17.0 release

---

charts/opentelemetry-collector/CHANGELOG.md
charts/opentelemetry-collector/Chart.yaml
charts/opentelemetry-collector/README.md

prepare release for opentelemetry-collector 1.3.0

chore: prep opentelemetry-collector 1.3.0 release

---

charts/honeycomb/CHANGELOG.md
charts/honeycomb/Chart.yaml

rel: prep for 1.7.0 release

---

charts/refinery/CHANGELOG.md
charts/refinery/Chart.yaml

rel: prep for 1.18.0 release

---

charts/refinery/Chart.yaml

chore: bump appVersion to 1.21

---

charts/honeycomb/CHANGELOG.md
charts/honeycomb/Chart.yaml

- prep release of honeycomb chart
- bump chart patch version

rel: prep honeycomb chart 1.7.1 release

---

charts/refinery/CHANGELOG.md
charts/refinery/Chart.yaml

- prep release of Refinery chart
- bump chart version

rel: prep refinery 1.19.0 release

---

charts/refinery/README.md
charts/refinery/templates/secretprovider.yaml
charts/refinery/values.yaml

This allows you to create your own secretProvider.
Adds a secretprovider.yaml and adds example values to the values.yaml
uncomment out the example and replace the environment name with the correct one.

feat: Add the ability to create your own Secret Provider

---

charts/refinery/CHANGELOG.md
charts/refinery/Chart.yaml

Prepare refinery chart 1.19.1 release
- Bump chart version

rel: prep Refinery 1.19.1 release

---

charts/secure-tenancy/Chart.yaml

depends on https://github.com/honeycombio/helm-charts/pull/247

maint: bump secure tenancy

---

charts/refinery/Chart.yaml
charts/refinery/values.yaml

- Closes https://github.com/honeycombio/helm-charts/issues/272
- bumps default Refinery version

maint: bump refinery version

---

charts/honeycomb/CHANGELOG.md
charts/honeycomb/Chart.yaml

Bump honeycomb chart version
- Bump honeycomb chart version
- Update changelog

rel: bump honeycomb chart to 1.8.0

---

charts/network-agent/Chart.yaml
charts/network-agent/values.yaml

Updating network-agent chart to use newer app version.
- Bump app version.
- Add more words to values.yaml about how headers will appear in data.

maint: [network-agent] bump app to v0.0.23-alpha

---

charts/network-agent/CHANGELOG.md
charts/network-agent/Chart.yaml

new chart to be published with latest network agent
- update version of chart
approve -> merge -> tag -> new chart published

rel: [network-agent] prep v0.0.4

---

charts/network-agent/README.md
charts/network-agent/templates/cluster_role.yaml

unnecessary extra lookups
- remove apps and metrics from rbac
everything should still work as well as it did before

maint: [network-agent] reduce apiGroups in rbac

---

charts/refinery/Chart.yaml

Updating Refinery chart to deploy [Refinery v2.4.1](https://github.com/honeycombio/refinery/releases/tag/v2.4.1)

maint: update Refinery app version to 2.4.1

---

charts/refinery/Chart.yaml

- Updating Refinery chart to deploy [Refinery v2.4.3](https://github.com/honeycombio/refinery/releases/tag/v2.4.3)

maint: update Refinery app version to 2.4.3

---

charts/refinery/Chart.yaml
charts/refinery/templates/deployment.yaml
charts/refinery/values.yaml

Updates health checks to use new Refinery health check endpoint.  Also removes any default values and sets some new values based on how Refinery now operates

fix(refinery): Update health check

---

charts/refinery/Chart.yaml

- Prep a Refinery v2.11.1 chart
- Bump deployed version of Refinery to v2.7.1

maint: prep Refinery chart v2.11.1

---

charts/refinery/Chart.yaml

Refinery 2.8.1 release
- bump minor version of refinery chart for Refinery 2.8.1
We are using the pre-released version internally

feat(refinery): release a new chart for Refinery 2.8.1

---

charts/refinery/Chart.yaml
charts/refinery/values.schema.json

- Can't current configure the OTelTracing config section because the schema doesn't allow it
- added `OTelTracing` to the schema
- tested locally

fix: Add OTelTracing to schema

---

charts/refinery/Chart.yaml

Update Refinery to the latest 2.9 release

maint(refinery): update appVersion to 2.9

---

charts/observability-pipeline/Chart.lock
charts/observability-pipeline/Chart.yaml
charts/observability-pipeline/templates/control-plane-deployment.yaml
charts/observability-pipeline/values.yaml

- adds feature to allow users to specify resources (requests/limits for memory and CPU) that the control plane can use.
- add new resoruces config option and hook into control plane deployment
- bump collector chart
Tested locally

feat: add resources support for control plane

---

charts/observability-pipeline/Chart.yaml
charts/observability-pipeline/values.yaml

Ensure logs from the process are emitted as with traces
Update the telemetry configuration to include a `logger_provider` section as well.
Update the chart and validate the data is emitted.

feat(observability-pipeline): Add logger provider configuration

---

charts/htp/Chart.lock
charts/htp/Chart.yaml
charts/htp/values.yaml

official release of the htp helm chart
- bump chart version
- update bindplane dep
- fix comment

rel(htp): release htp chart

---

charts/observability-pipeline/Chart.yaml
charts/observability-pipeline/templates/NOTES.txt
charts/observability-pipeline/templates/_helpters.tpl
charts/observability-pipeline/templates/collector-deployment.yaml
charts/observability-pipeline/templates/control-plane-configmap-otel.yaml
charts/observability-pipeline/templates/control-plane-deployment.yaml
charts/observability-pipeline/templates/control-plane-service.yaml
charts/observability-pipeline/templates/control-plane-serviceaccount.yaml
charts/observability-pipeline/values.yaml

Updating names in observability-pipeline helm charts.

maint(observability-pipeline): update naming

---

charts/refinery/Chart.yaml

new helm chart for updated refinery
- update refinery to [v2.9.3](https://github.com/honeycombio/refinery/releases/tag/v2.9.3)
- update chart version to 2.15.4

maint(refinery): upgrade to refinery v2.9.3

---

charts/observability-pipeline/Chart.yaml
charts/observability-pipeline/templates/_helpers.tpl

Beekeeper uses identification attribute in AgentDescription to differentiate different agent types. This PR adds it for collector.
- add `identifying_attributes` for collector config
local testing

feat(observability-pipeline): add agent identification attributes for collector

---

charts/observability-pipeline/Chart.yaml
charts/observability-pipeline/templates/NOTES.txt

Improves the install message for the observability-pipeline chart
Related to https://app.asana.com/0/1208469935858869/1209582431136178
- Update install note
Tested locally

feat(observability-pipeline): improve install message

---

charts/observability-pipeline/Chart.yaml
charts/observability-pipeline/templates/_helpers.tpl

Increases the opampsupervisor's default config timeout to solve config update issue

fix(observability-pipeline): increase config apply timeout

---

README.md

Provide accurate documentation of each directory in this helm chart repo

maint(docs): update README.md

---

charts/observability-pipeline/Chart.yaml
charts/observability-pipeline/values.yaml

Enables more telemetry by default
- enable beekeeper telemetry
- enable refinery honeycomb logger

feat(observability-pipeline): enable more telemetry by default

---

charts/observability-pipeline/Chart.yaml
charts/observability-pipeline/values.yaml

This is not generating any useful metrics at this time.

feat: remove metrics configuration for supervisor

---

charts/observability-pipeline/Chart.yaml
charts/observability-pipeline/values.yaml

- Closes provides a default image for the supervised collector

feat(observability-collector): add default supervised-collector image

---

charts/observability-pipeline/Chart.yaml
charts/observability-pipeline/templates/beekeeper-deployment.yaml
charts/observability-pipeline/values.yaml

Adds support for enabling markers support in beekeeper
- add new default env var
- hookup env var to beekeeper contain
local kind cluster

feat(observability-pipeline): add markers support

---

charts/observability-pipeline/Chart.yaml
charts/observability-pipeline/templates/_helpers.tpl

update the collector service.name

maint(observability-collector): update service name

---

charts/refinery/Chart.yaml

Updates Refinery to v2.9.4.
- Update version and appVersion

maint(refinery): Update refinery to 2.9.4

---

charts/observability-pipeline/Chart.yaml
charts/observability-pipeline/values.yaml

fix: update opamp url

---

charts/htp/Chart.yaml

Updating the bindplane helm chart to update the bindplane version to apply patch fixes to bindplane.
Update the bindplane helm chart version, bindplane control plane version, and the bindplane dependency version
Check the bindplane deploy can access this chart.

maint(bindplane): update bindplane chart version

---

charts/htp/Chart.lock
charts/htp/Chart.yaml

Last week, Bindplane put out https://github.com/observIQ/bindplane-op-helm/pull/204 so we should match them.

maint(htp): upgrade bindplane version

---

charts/refinery/Chart.yaml
charts/refinery/values.schema.json

Add experimental OpAMP configuration to schema.

feat(refinery): update schema

---

charts/observability-pipeline/Chart.lock
charts/observability-pipeline/Chart.yaml
charts/observability-pipeline/values.yaml

This updates the refinery configuration options for the experimental opamp support.

feat: update observability pipeline chart refinery options

---

charts/observability-pipeline/Chart.yaml
charts/observability-pipeline/templates/_helpers.tpl
charts/observability-pipeline/values.schema.json
charts/observability-pipeline/values.yaml

Before I merged https://github.com/honeycombio/helm-charts/pull/469 I forgot to update the newly added schema file.
- clean up schema file
- Fix some extra spacing
- tidy up agent service name
helm template.

fix(observability-pipeline): cleanup schema file

---

charts/observability-pipeline/Chart.yaml
charts/observability-pipeline/values.yaml

- updates the collector's metrics to be delta temporality.
- related to https://github.com/honeycombio/pipeline-team/issues/360
- set delta temporality on collector metrics
- update collector to use new headers style so that it honors the temporality setting
- update all images to latest
sippycup

feat(observability-pipeline): update collector metrics to be delta

---

charts/observability-pipeline/Chart.yaml

I didn't properly bump the chart version

fix(observability-pipeline): bump chart version

---

charts/observability-pipeline/Chart.yaml
charts/observability-pipeline/templates/beekeeper-deployment.yaml
charts/observability-pipeline/values.schema.json
charts/observability-pipeline/values.yaml
tests/observability-pipeline/rendered/rendered-eu.yaml
tests/observability-pipeline/rendered/rendered-unset-region.yaml

- related to https://github.com/honeycombio/pipeline-team/issues/401
- adds env var for batching deployments. Set a default value based on default replica counts and 
- add comments for new value
tested via sippycup

feat(observability-pipeline): support batching deployments

---

charts/htp-builder/Chart.yaml
charts/htp-builder/values.yaml

bumps refinery to 2.9.6. Also fixes a typo

maint(htp-builder): bump default refinery version

---

README.md
charts/htp/Chart.yaml
charts/htp/README.md

Update READMEs with name changes

maint(htp): update readme with htp-builder
