honeycombio/helm-charts

- honeycomb/Chart.yaml
- honeycomb/README.md
- honeycomb/templates/NOTES.txt
- honeycomb/templates/agent-daemonset.yaml
- honeycomb/templates/events-deployment.yaml
- honeycomb/templates/metrics-deployment.yaml
- honeycomb/templates/secret.yaml
- honeycomb/values.yaml
- opentelemetry-collector/Chart.yaml
- opentelemetry-collector/README.md
- opentelemetry-collector/templates/NOTES.txt
- opentelemetry-collector/templates/deployment.yaml
- opentelemetry-collector/templates/secret.yaml
- opentelemetry-collector/values.yaml
Added checksum annotation(s) to all deploy pods. Updating a config setting or API key will now force a restart on all affected pods with a `helm upgrade ...` command.
> checksums for config and secrets

- opentelemetry-collector/Chart.yaml
- opentelemetry-collector/README.md
- opentelemetry-collector/values.yaml
Moving to 0.6.0 of the OpenTelemetry-Collector.
OpenTelemetry introduced a breaking change to the OTLP receiver configuration. The risk for those affected is very low since the change is contained within the default config of this chart.
Chart minor version is bumped because of the change.
> Use OpenTelemetry-Collector 0.6.0

- README.md
- secure-tenancy/.helmignore
- secure-tenancy/Chart.lock
- secure-tenancy/Chart.yaml
- secure-tenancy/README.md
- secure-tenancy/resources/Dockerfile
- secure-tenancy/templates/NOTES.txt
- secure-tenancy/templates/_helpers.tpl
- secure-tenancy/templates/configmap.yaml
- secure-tenancy/templates/deployment.yaml
- secure-tenancy/templates/hpa.yaml
- secure-tenancy/templates/ingress.yaml
- secure-tenancy/templates/migrate-job.yaml
- secure-tenancy/templates/migrate-secret.yaml
- secure-tenancy/templates/secret.yaml
- secure-tenancy/templates/service.yaml
- secure-tenancy/values.yaml
Helm chart to install Secure Tenancy.  Requires user to build and supply an image on private repository for Secure Tenancy binary.  
- Easy to get going, by default it will setup and install a MySQL database to use
- Can also use an existing MySQL database instead
- Migrate script will run with `helm install` commands, as either a post-install (when install MySQL) or pre-install (when using an existing MySQL) hook.
- Includes support for Ingress
- Includes support for horizontal pod autoscaling
> Secure Tenancy chart

- release.sh
- secure-tenancy/Chart.lock
- secure-tenancy/Chart.yaml
Adds dependency build to release script.
Also locked the mariadb dependency on secure-tenancy to version 7.6.1
> Fix release script (for secure-tenancy)

- honeycomb/templates/config.yaml
Currently the ConfigMap is only created when rbac.create=true, even though it's not an RBAC resource.
We've installed the chart with `rbac.create=false` to manage the RBAC resources out-of-band, but this caused the ConfigMap not to get installed. I can't think of a reason why the ConfigMap should be gated on `rbac.create`, or a reason to gate it on anything at all, but I'm happy to add a `configmap.create` or similar value if that would be useful.
> Always create ConfigMap

- honeycomb/templates/rbac.yaml
- opentelemetry-collector/README.md
- opentelemetry-collector/templates/_helpers.tpl
- opentelemetry-collector/templates/deployment.yaml
- opentelemetry-collector/templates/k8sProcessor-cluster-role.yaml
- opentelemetry-collector/templates/k8sProcessor-rbac.yaml
- opentelemetry-collector/templates/serviceaccount.yaml
- opentelemetry-collector/values.yaml
Can easily create the roles and service accounts required to use the k8s_tagger.
> Add in k8s tagger config

- honeycomb/Chart.yaml
- honeycomb/templates/daemonset.yaml
Adding NODE_IP allows for seamless functionality in some managed clusters that don't have DNS entries for node names.
This depends on [Honeycomb Agent PR 145](https://github.com/honeycombio/honeycomb-kubernetes-agent/pull/145) to be merged and released first.
> Add NODE_IP to agent configuration

- .circleci/config.yml
- .circleci/release.sh
Uses proper CircleCI env variables and context for release. 
To setup in CircleCI we need the following environment variable setup:
CHARTS_REPO: `https://honeycombio.github.io/helm-charts`
Also removes an unneeded shellcheck on the release script which ran on every commit to main. In the future we should add a helm linter
> Fix CircleCI release

- charts/refinery/README.md
- charts/refinery/sample-configs/config_complete.yaml
- charts/refinery/sample-configs/rules_complete.yaml
Includes YAML equivalents of the config_complete.toml and rules_comlete.toml files from the Refinery repo
These files are meant to be used as examples for users.
> Add sample configs for Refinery

- charts/refinery/README.md
- charts/refinery/sample-configs/config_complete.yaml
- charts/refinery/templates/deployment.yaml
- charts/refinery/templates/service.yaml
- charts/refinery/values.yaml
This will enable by default port 4317 for incoming OTLP traffic (using gRPC).  
4317 was chosen because that is what the OpenTelemetry Collector is moving towards for receiving OTLP traffic over grpc. 
This will also clear up potential confusion over using the same port as the Prometheus metrics receiver, as previously referenced in the sample config.
> [refinery] - enable port 4317 for OTLP

- charts/refinery/README.md
- charts/refinery/sample-configs/config_complete.yaml
- charts/refinery/sample-configs/rules_complete.yaml
- charts/refinery/values.yaml
- charts/secure-tenancy/Chart.yaml
Adjusts limits to be in line with what is expected in production deployments.
Replica Count -> 3
Memory Limit -> 2GB
InMemoryCollector.MaxAlloc -> (85% of 2GB)
TraceTimeout -> 60s
This also adds lots of docs for each setting inside of the primary values.yaml file allowing users an easier way to understand each setting, and how to build their own values file.
> [refinery] - adjust limits for production

- charts/refinery/templates/deployment-redis.yaml
- charts/refinery/templates/service-redis.yaml
Updates the service port name for Redis to properly represent its use.  Fixes #42
> [refinery] - redis service port name

- charts/refinery/Chart.yaml
- charts/refinery/README.md
Bumps chart minor version up because this release has some upgrade concerns which are noted in the readme.
> [refinery] - prep for 1.1.0 release

- charts/opentelemetry-collector/Chart.yaml
- charts/opentelemetry-collector/values.yaml
Change the protocol for jaeger-compact and jaeger-binary to
UDP from TCP.
Ref: https://www.jaegertracing.io/docs/1.22/getting-started/
> Change jaeger thrift ports

- charts/opentelemetry-collector/Chart.yaml
- charts/opentelemetry-collector/README.md
- charts/opentelemetry-collector/templates/configmap.yaml
- charts/opentelemetry-collector/values.yaml
Exposes export options for the default OTLP exporter. All OTLP exporter options but `endpoint` and `headers` can be specified.
Fixes #48
> [opentelemetry-collector] - expose exporter options for OTLP

- charts/opentelemetry-collector/Chart.yaml
- charts/opentelemetry-collector/README.md
- charts/opentelemetry-collector/templates/configmap.yaml
- charts/opentelemetry-collector/values.yaml
Introduces a new property `honeycomb.useHoneycombExporter` (default false) which can be used to leverage the old Honeycomb format exporter, instead of the OTLP exporter.
This is being done to allow some customers to use the collector with other Honeycomb technologies which don't yet support OTLP.
> [opentelemetry-collector] add option for old exporter

- charts/secure-tenancy/Chart.yaml
- charts/secure-tenancy/README.md
- charts/secure-tenancy/templates/configmap.yaml
- charts/secure-tenancy/templates/deployment.yaml
- charts/secure-tenancy/templates/service.yaml
- charts/secure-tenancy/values.yaml
Adds support to ingest OTLP over GRPC ingest into Secure Tenancy.
Closes #49
> [secure-tenancy] add otlp over grpc support

- charts/honeycomb/Chart.yaml
- charts/honeycomb/README.md
- charts/honeycomb/templates/daemonset.yaml
- charts/honeycomb/values.yaml
Adds support for [priorityClassName](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/) to agent daemonset.
Closes #45
> [agent] - add support for priorityClassName

- charts/refinery/Chart.yaml
- charts/refinery/README.md
- charts/refinery/templates/deployment-redis.yaml
- charts/refinery/values.yaml
Adds support for all pod scheduling options specific to the Redis deployment. Adds the following parameters:
`redis.nodeSlector`
`redis.tolerations`
`redis.affinity`
Closes #56 
This PR also adds clarifying information that the default Redis install should not be used for highly available production architectures.
> [refinery] - support pod scheduling specific for redis 

- charts/honeycomb/README.md
While reading the doc, I got confused about whether I should have a top-level `agent.watchers`. The last paragraph told me that `agent.` is no longer used, so this change seems correct.
Change `agent.watchers` to `watchers`
> Fix reference to `agent.watchers`

- charts/refinery/Chart.yaml
- charts/refinery/README.md
- charts/refinery/templates/ingress-beta.yaml
- charts/refinery/values.yaml
Starting with Kubernetes 1.19, the ingress controller was made stable. In Kubernetes >= 1.20 a warning will be displayed if the beta is used, with 1.22 marking when the beta is deprecated. 
This PR defines 2 ingresses that will be installed exclusively of each other. Depending on the version of the target Kubernetes (>=1.19, or <1.19) the stable or beta version of the ingress will be installed.
To keep the ingress simple, and avoid potential configuration confusion, support for multiple paths has also been removed. Frankly, it never worked before, so this is a low risk removal.
fixes #54
> [refinery] update ingress support for k8s >= 1.19

- charts/refinery/Chart.yaml
- charts/refinery/README.md
- charts/refinery/templates/deployment.yaml
- charts/refinery/templates/hpa.yaml
- charts/refinery/values.yaml
Adds support for dynamic autoscaling using an HPA. The default autoscaling configuration is to disable scaledown, as scaling events can cause traces with missing spans.  The documentation explains this.
> [refinery] add HPA support

- charts/secure-tenancy/Chart.yaml
- charts/secure-tenancy/README.md
- charts/secure-tenancy/templates/ingress-beta.yaml
Starting with Kubernetes 1.19, the ingress controller was made stable. In Kubernetes >= 1.20 a warning will be displayed if the beta is used, with 1.22 marking when the beta is deprecated.
This PR defines 2 ingresses that will be installed exclusively of each other. Depending on the version of the target Kubernetes (>=1.19, or <1.19) the stable or beta version of the ingress will be installed.
Also bumps version of secure-tenancy to 1.10.1
And finally updates the chart's version to 1.0.0 (long overdue).
fixes #55
> [secure-tenancy] update ingress support for k8s >= 1.19

- charts/secure-tenancy/templates/migrate-job.yaml
- charts/secure-tenancy/templates/migrate-secret.yaml
The location of the migrate script for Secure Tenancy has moved to a sub-folder called `/migrate/mysql`.
> [secure-tenancy] fix migrate script

- RELEASING.md
- charts/honeycomb/CHANGELOG.md
- charts/opentelemetry-collector/CHANGELOG.md
- charts/refinery/CHANGELOG.md
- charts/secure-tenancy/CHANGELOG.md
Changes:
- A `CHANGELOG.md` file has been added for each chart based on changes described in past release notes. These can be updated as part of the release process.
- The releasing process has also been updated to minimize GH releases and more closely resemble the process on some other repos. By always having a 'prep-release' branch, it should hopefully be easier to ensure the latest commit to `main` is for the correct release.
> [maint] Add changelogs and update releasing process

- charts/refinery/Chart.yaml
- charts/refinery/README.md
- charts/refinery/sample-configs/config_complete.yaml
- charts/refinery/values.yaml
Upgrade Refinery Helm Chart to [v1.8.0](https://github.com/honeycombio/refinery/releases/tag/v1.8.0)
This new version adds a configurable option for MaxBatchSize, with a set default of 500 (previous hardcoded default)
> [refinery] Upgrade Refinery to v1.8.0, for configurable MaxBatchSize

- charts/honeycomb/CHANGELOG.md
- charts/honeycomb/Chart.yaml
Prep honeycomb kubernetes agent helm chart release v1.1.1
- Changelog updated for v1.1.1 for fixes made in kubernetes agent
- Chart versions updated for chart v1.1.1 and kubernetes agent v2.2.1
> [k8s] Prep honeycomb kubernetes agent helm chart release v1.1.1

- charts/honeycomb/CHANGELOG.md
- charts/honeycomb/Chart.yaml
chart for agent release [2.3.0](https://github.com/honeycombio/honeycomb-kubernetes-agent/releases/tag/v2.3.0)
> agent: prepare release 1.2.0

- charts/honeycomb/templates/cluster-role.yaml
In https://github.com/honeycombio/honeycomb-kubernetes-agent/pull/200 we added the option to add node metadata labels to metric events in the honeycomb-kubernetes-agent. In order to list nodes, the ClusterRole requires access to the nodes resource. We'll only include this resource if the `includeNodeLabels` config value is true.
> add nodes resource to honeycomb/templates/cluster-role

- charts/honeycomb/Chart.yaml
* fixes nil pointer deref when includeNodeLabels is enabled
> [honeycomb] bump agent version to 2.3.1

- charts/opentelemetry-collector/Chart.yaml
- charts/opentelemetry-collector/templates/deployment.yaml
Updates to the latest version of the OpenTelemetry collector (0.43.0)
Because of a change in executable, and we should be following best practices here anyhow, this also removes the `command` property, and instead just uses `args`, which will allow the base image to define the entrypoint.
> [opentelemetry-collector] - update to collector 0.43.0

- charts/refinery/README.md
- charts/refinery/templates/deployment.yaml
- charts/refinery/values.yaml
This PR is a workaround for the issue describe in #101
> Allow operators to disable live reload of Refinery related to changed sampling rules

- charts/secure-tenancy/Chart.yaml
- charts/secure-tenancy/README.md
- charts/secure-tenancy/templates/configmap.yaml
- charts/secure-tenancy/values.yaml
This updates the Secure Tenancy chart to support Release 1.12.1 of Secure Tenancy, including adding support for the new max_parallelism configuration value. A few edits were also made to documentation and readme.
The editor also brought the edited files up to markdown formatting standards, so there are also a bunch of whitespace changes; use github's "ignore whitespace" feature to trim this down to the minimum diffs if necessary.
Closes #102
> Update ST chart to support 1.12.1

- .github/CODEOWNERS
For now the @honeycombio/telemetry-team are managing all charts, including the Secure-Tenancy one. This PR removes the team override for now so we can approve and merge PRs.
> Remove secure-tenancy chart owner override

- charts/opentelemetry-collector/CHANGELOG.md
- charts/opentelemetry-collector/Chart.yaml
Prepares the v1.1.0 release of the OpenTelemtry Collector chart.
- Adds changelog entry
- Updates chart version to 1.1.0
> Prepare otel collector chart v1.1.0 release

- .circleci/config.yml
Closes #122 
CircleCI machine executor when set to `machine: true` uses Ubuntu 14.04 image which is [being deprecated](https://circleci.com/blog/ubuntu-14-16-image-deprecation/). Following [Circle guidance for migration](https://circleci.com/docs/2.0/images/linux-vm/14.04-to-20.04-migration/), the image is now specified as the supported Ubuntu 20.04.
> maint: use supported ubuntu image for circle

- charts/refinery/Chart.yaml
- charts/refinery/values.yaml
Updates the Refinery chart's image to use the latest (v1.11.0).
- Closes #124 
Includes adding `EnvironmentCacheTTL` to values.yaml.
> [refinery] Bump image to v1.11.0

- charts/refinery/templates/ingress-beta.yaml
- charts/refinery/templates/ingress-grpc.yaml
- charts/refinery/templates/ingress.yaml
- charts/secure-tenancy/Chart.yaml
- charts/secure-tenancy/README.md
- charts/secure-tenancy/templates/configmap.yaml
- charts/secure-tenancy/templates/ingress-beta.yaml
- charts/secure-tenancy/templates/ingress.yaml
- charts/secure-tenancy/values.yaml
This adds support for [ingressClassName](https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation) which is a more recent feature of Kubernetes.
Closes #94.
> support ingressClassName

- charts/refinery/Chart.yaml
- charts/refinery/sample-configs/rules_complete.yaml
update refinery chart appVersion to [v1.13.0](https://github.com/honeycombio/refinery/releases/tag/v1.13.0).
This version adds parsing for nested json fields in the rules sampler.
> [refinery] update to refinery v1.13.0 with nested fields

- charts/honeycomb/CHANGELOG.md
- charts/honeycomb/Chart.yaml
- update version of honeycomb kubernetes agent chart to 1.5.1
- add changelog entry
> [honeycomb] prep honeycomb kubernetes agent chart version 1.5.1

- charts/refinery/templates/deployment.yaml
- charts/refinery/values.yaml
These changes enable users to define additional `volume` and `volumeMount` configurations for the Refinery deployment object. This is important to enable volume-based secrets handling techniques such as the [secrets-store-csi-driver](https://secrets-store-csi-driver.sigs.k8s.io/).
Adds two new helm values: `volumes: [ ]` and `volumeMounts: [ ]`, uses the existing patterns to call the values using `toYaml` and `nindent`.
From `./charts/refinery`, I am able to confirm that the chart renders properly _without_ the values set:
```
% helm template -f values.yaml .
```
and _with_ the values set:
```
% cat /tmp/volumes.values.yaml  
extraVolumeMounts:
- name: honeycomb-secrets
mountPath: "/mnt/secrets-store"
readOnly: true
extraVolumes:
- name: honeycomb-secrets
csi:
driver: …
```
> [Refinery] Enable extra volume configurations in deployment config

- charts/opentelemetry-collector/templates/configmap.yaml
- charts/opentelemetry-collector/templates/deployment.yaml
- charts/opentelemetry-collector/templates/hpa.yaml
- charts/opentelemetry-collector/templates/secret.yaml
- charts/opentelemetry-collector/templates/service.yaml
- charts/opentelemetry-collector/templates/serviceaccount.yaml
- Closes #146
While helm install can respect the kubectl context namespace or accept a namespace flag, when using helm template, this information is lost if not persisted to the generated files. This means tooling that requires a helm template -> kubectl install has to work around the missing namespace.
Adds in the default `.Release.Namespace` value to the namespace for each namespace resource. https://helm.sh/docs/chart_template_guide/builtin_objects/ . Similar changes have been made such as https://github.com/helm/charts/pull/17937/files#diff-4dcbfca5f8fd1c82a179cf60e0448926548323d101f0321679e2fd1e3a2dc665R12  found on the original issue https://github.com/helm/helm/issues/5465
```
❯ kns
Context "ngrok-dev-us" modified.
Active namespace is "default".
❯ helm template …
```
> Add helm namespace to templates

- charts/honeycomb/Chart.yaml
Updates [honeycomb-kubernetes-agent](https://github.com/honeycombio/honeycomb-kubernetes-agent) to 2.5.3 which has a fix for the latest OpenSSL CVE.
- Closes https://github.com/honeycombio/telemetry-team/issues/263
- Updates `appVersion` in the Honeycomb helm chart to 2.5.3
The 2.5.3 was a no-op release that was made to rebuild the docker image so there should be no changes in any functionality.
> update honeycomb k8s agent to 2.5.3

- charts/refinery/sample-configs/rules_complete.yaml
Signed-off-by: Irving Popovetsky <irving@honeycomb.io>
The YAML in the `rules_complete.yaml` file is invalid due to duplicate keys.  This PR fixes that, more closely matching the intent from the TOML version.
> Fix a TOML->YAML conversion whoopsie

- charts/refinery/values.yaml
Without this if you removed the comment in front of `RedisUsername` it would be a YAML syntax error.
> Use correct syntax in commented out field

- charts/opentelemetry-collector/Chart.yaml
- charts/opentelemetry-collector/templates/hpa.yaml
Really this is for https://github.com/argoproj/argo-cd/issues/1079 which points blame at upstream k8s.
https://github.com/argoproj/argo-cd/issues/1079
This issue points at upstream k8s as the problem, but for the moment it's easier to request a change here that matches the output of the HPA object
Swapping the CPU and memory metric for the HPA
Nothing should change other than the resulting order of the rendered template
> [opentelemetry-collector] Swap order of hpa spec.metrics

- charts/refinery/sample-configs/rules_complete.yaml
Refinery would reject the EMADynamic Sampler rule without this change.
Yaml parser doesn't like the dot in the middle of multiple fields.
Fixing the parser is a bit beyond my skill level.
Simplifying the example so it works is the sweet spot.
Run refinery in debug mode with a breakpoint in the rule parser to see that line fail to parse in the old config and succeed in the new config.
> separate yaml layers to help parsing

- charts/refinery/templates/deployment.yaml
- charts/refinery/values.yaml
```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.volumes[0].projected.sources[1].configMap): invalid type for io.k8s.api.core.v1.ConfigMapProjection: got "array", expected "map"
```
- Closes #<enter issue here>
Remove obsolete dash from configmap names within `deployment.yaml` template
Run below
```
helm install refinery ./refinery
```
expected output
```
NAME: refinery
LAST DEPLOYED: Tue Aug 23 13:05:18 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Honeycomb refinery is setup and configured to refine events that are sent through it. You should see data flowing
within a few minutes at https://ui.honeycomb.io
```
> fix: Remove obsolete dash from configmap names

- charts/refinery/templates/configmap-config.yaml
- charts/refinery/templates/configmap-rules.yaml
- charts/refinery/templates/deployment-redis.yaml
- charts/refinery/templates/deployment.yaml
- charts/refinery/templates/hpa.yaml
- charts/refinery/templates/ingress-beta.yaml
- charts/refinery/templates/ingress-grpc.yaml
- charts/refinery/templates/ingress.yaml
- charts/refinery/templates/service-redis.yaml
- charts/refinery/templates/service.yaml
- charts/refinery/templates/serviceaccount.yaml
This allows generating the namespace and have it defined based on the kubectl client's namespace flag
See Issue https://github.com/honeycombio/helm-charts/issues/146 for context around the problem
- Closes [#157](https://github.com/honeycombio/helm-charts/issues/157)
Please see the same PR for the Collector which makes the same changes: https://github.com/honeycombio/helm-charts/pull/155
> Add Helm namespace metadata

- charts/refinery/Chart.yaml
- charts/refinery/values.yaml
- [Refinery 1.17.0 is released!](https://github.com/honeycombio/refinery/releases/tag/v1.17.0)
- closes #181 
Installed the Refinery helm chart locally with the new config values 👍
> [refinery] bump app version to 1.17.0

- charts/honeycomb/Chart.yaml
Updates the Honeycomb Kubernetes Agent app version to latest.
- updates app version to 2.5.4
- Using the chart uses the latest version of the Kubernetes agent
> [honeycomb] update k8s agent version to v2.5.4

- charts/honeycomb/CHANGELOG.md
- charts/honeycomb/Chart.yaml
Prepares the honeycomb kubernetes agent v1.5.3 release.
- Update chart version to 1.5.3
> [honeycomb] Prepare v1.5.3 release

- charts/refinery/templates/configmap-config.yaml
- charts/refinery/values.yaml
Currently the refinery chart must be installed with a release name of `refinery` or the `.Values.config.PeerManagement.RedisHost` must be manually updated to match the release name.  This works if you know what the release name will be, but for situations like chart-testing, the release name is dynamically generated.  It is also problematic when using the chart for the first time; if you want to use the default values.yaml you must use `refinery` as the release name.
Updates `.Values.config` to be run through the `tpl` function.  This allows us to set `RedisHost: '{{include "refinery.redis.fullname" .}}:6379'` in the values.yaml and us the chart's fullname helpers to determine the default RedisHost.
Deployed refinery local and ran it through chart-testing.
> [refinery] Update to set redis host based on release name

- charts/refinery/Chart.yaml
- charts/refinery/ci/cache-overrun-strat-resize-values.yaml
- charts/refinery/values.yaml
- [Refinery 1.19.0 is released!](https://github.com/honeycombio/refinery/releases/tag/v1.19.0)
- Updates refinery configuration options to be in line with what was added in refinery 1.19.0
- closes #202
Installed the Refinery helm chart locally with the new config values 👍 
Added new CI scenario for `CacheOverrunStrategy: resize`
> [refinery] bump app version to 1.19.0

- charts/opentelemetry-collector/templates/hpa.yaml
- charts/refinery/templates/hpa.yaml
- charts/secure-tenancy/templates/hpa.yaml
- Closes #212 
Updates the ApiVersion of the HorizontalPodAutoscaler resources to autoscaling/v2. This is fix compatability with K8s 1.26 onwards.
I've also updated the ordering of the resource metrics, to ensure consistency with: https://github.com/honeycombio/helm-charts/pull/164
> maint: Update HPAs to autoscaling/v2

- charts/refinery/templates/hpa.yaml
- charts/secure-tenancy/templates/hpa.yaml
- Closes https://github.com/honeycombio/helm-charts/issues/216
Changes the ordering of the resouce metrics in the `refinery` and `secure-tenancy` charts to have memory before cpu. This ensures consistency with the HPA in the `opentelemetry-collector` chart, and stops ArgoCD from thinking these HPAs are always out of sync.
> fix: Updated ordering of CPU/Memory resource metrics

- charts/refinery/templates/service.yaml
Port mapping is useful for testing refinery locally. Adding this to the `service.yaml` so that it does not need to manually be added by anyone needing to reference this helm chart.
> chore: add nodeport to the service.yaml

- charts/honeycomb/Chart.yaml
- Closes https://github.com/honeycombio/helm-charts/issues/225
- bump appVersion to 2.7.0
- Ran locally in a kind cluster
> maint: Bump honeycomb chart appVersion to 2.7.0

- charts/refinery/Chart.yaml
- charts/refinery/templates/NOTES.txt
- charts/refinery/values.yaml
- Closes https://github.com/honeycombio/helm-charts/issues/223
- Updates refinery chart to use refinery 1.20.0 by default.  Updated values.yaml with new configuration fields.  Updated `NOTES.txt` to log [INFO] when values are not set to recommended values.
Local kind cluster.
> maint: Update refinery chart to use refinery 1.20.0

- charts/honeycomb/Chart.yaml
- Closes https://github.com/honeycombio/helm-charts/issues/233
- Bumps default Honeycomb k8s agent version to 2.7.1
CI tests
> maint: bump honeycomb chart appVersion

- charts/opentelemetry-collector/README.md
- charts/opentelemetry-collector/templates/NOTES.txt
- Related to https://github.com/honeycombio/helm-charts/issues/231
- Updates the collector chart's readme with a Sunset notice.
> maint: Add Sunset notice to collector README

- charts/honeycomb/README.md
- charts/honeycomb/templates/daemonset.yaml
- charts/honeycomb/values.yaml
Adding additional custom env variables to honeycomb
- Closes #241
extending config to read env variable from a user values file.
adding proxy setting like this will add them to the chart
```yaml
additionalEnv:
- name: HTTP_PROXY
value: http://your-proxy-url.example:8080
```
> feat: Added support for additional env variable settings

- charts/secure-tenancy/Chart.lock
- charts/secure-tenancy/Chart.yaml
The secure-tenancy 1.2.1 release didn't work bc the chart dependency no longer existed.  The packager needed to be able to pull the dependency to package and release the chart.
Updates bitnami mariadb chart to latest version so releasing works.
> maint: fix secure-tenancy dependency url

- .circleci/install_tools.sh
- charts/secure-tenancy/Chart.yaml
Updates our helm release tools to be up-to-date.  This is necessary to use oci repository urls.  See https://app.circleci.com/pipelines/github/honeycombio/helm-charts/645/workflows/d4873a2d-4a88-4b1c-b553-e8f186f61580/jobs/265
Update to use latest helm and chart releaser
Tested that cr package worked with these versions locally.
> maint: Bump release tooling

- .circleci/config.yml
- .circleci/release.sh
With the bump to chart releaser 1.5.0 we lost the ability to do `cr index` with an `ssh` git remote; the tool now requires us to use an `https` remote.  For the `v1.2.3-secure-tenancy` release I had to do the `cr index` step manually from my laptop. See and https://github.com/helm/chart-releaser/issues/124.
The PR solves this problem and also removes some deprecated flags and unused env vars.
- set git remote to https url for `cr index` step.
- remove unused `--charts-repo` flag
- remove unused variables.
I couldn't :/ but I'll try to do a honeycomb chart release once this is merged to test it.
> maint: cleanup release

- .circleci/release.sh
- Closes https://github.com/honeycombio/helm-charts/issues/252
- updates the release script to unset an `insteadOf` config in the global git config of the circleci job.
Tested that the git remote is set properly.  Can't test the actual `cr index` command until the next release.
> fix: Unset insteadOf in git config of release job

- charts/refinery/values.yaml
The MaxConnectionAge default is 0 which leads to load balancers failing to re-balance GRPC connections to Refinery. This means that one node in a multi-node deployment receives all of the traffic and expends more resources than it should redirecting all the traffic while the other nodes sit idle. 
This PR doesn't change the default but exposes it as a configuration that can be set so operators can be in a better position to fix the problem if they run into it. 
Adds some new  
You can use the `helm template` command to see that the config is present. When it comes to actually verifying the connections remain open, I haven't cracked that nut yet.
> docs: [refinery] Add MaxConnectionAge default to values.yaml

- charts/refinery/ci/debug.yaml
- charts/refinery/templates/_helpers.tpl
- charts/refinery/templates/configmap-config.yaml
- charts/refinery/templates/deployment.yaml
- charts/refinery/values.yaml
pprof endpoints are not enabled by default and cannot easily be enabled since the argv isn't editable from the variables passed to the helm template by users.
Enables the -d flag by default, which cause the container to listen on the :6060 debug service name.
> feat: enable debug service by default

- charts/refinery/values.yaml
Accidentally set debug.enabled to true in https://github.com/honeycombio/helm-charts/pull/255
- sets debug.enabled to false
> fix: disable debug by default

- charts/refinery/values.yaml
- Fixes an issue where the 2.0.0 version of the chart did not correctly set `GRPCServerParameters.ListenAddr` default.  This meant that the 2.0.0 version of the chart does not enable otlp endpoint by default.
- add back `GRPCServerParameters.ListenAddr` with the proper default value.
Tested in local kind cluster.
> fix: [refinery] Add default GRPCServerParameters.ListenAddr

- charts/refinery/templates/deployment.yaml
- fixes issue where the template was using `.Values.LiveReloade` instead of `.Values.Live.Reload`.
- fix typo
`helm template`
> fix: Fix typo with `LiveReload`

- charts/refinery/README.md
- charts/refinery/templates/deployment.yaml
- charts/refinery/values.yaml
- Inability to specify any refinery commands, such as `--no-validate`
- add new `extraCommandArgs` field.
- apply `extraCommandArgs` field to refinery command args.
Manual test with local kind cluster
> feat: Add ability to specific extra refinery commands

- charts/refinery/values.yaml
- Refinery 2.0.0 incorrectly listed redis as the default peer management type when it is actually file.
- updates the helm chart to use redis peer management by default
Locally in kind cluster
> fix: Update peer management to use redis

- charts/refinery/values.yaml
- 2.0.0 chart dropped AddRuleReasonToTrace
- Add back appropriate RefineryTelemetry settings to match values used in 1.19.1
Tested locally
> fix: Add back addrulereasontotrace

- charts/refinery/ci/rules-values.yaml
- charts/refinery/templates/_helpers.tpl
- charts/refinery/templates/configmap-rules.yaml
- charts/refinery/values.schema.json
- charts/refinery/values.yaml
- The include of a default in the values.yaml led to some confusion.  In order to override the default rule you had to explicitly set `.Values.rules.Samplers.__default__.DeterministicSampler: null`, which, while 100% correct in helm, is a little unintuative.
- Updates the chart to only set a default rule if none is supplied by the user.  This ensures that Refinery always has a default rule, but won't mess with any users supplied configuration.
Tested locally and added a new CI scenario
> fix: Fix issue where default rule was always present unless explicitly disabled.

- charts/refinery/templates/deployment.yaml
- charts/refinery/templates/service.yaml
- Closes https://github.com/honeycombio/helm-charts/issues/273
- Fixes typo where `enabled` was used instead of `Enabled`
Tested with `helm template`
> fix: [refinery] Fix issue where Prometheus ports are not enabled when PrometheusMetrics is enabled

- charts/refinery/Chart.yaml
Bumps default refinery version to 2.1.0
- Closes https://github.com/honeycombio/helm-charts/issues/281
> maint: Bump refinery version

- charts/refinery/README.md
- charts/refinery/values.schema.json
- charts/refinery/values.yaml
- Closes https://github.com/honeycombio/helm-charts/issues/286
- Updates the json schema file to enforce operator field to be required and have a length of at least 1
- Update the values.yaml and README with a warning to stringify certain operators
Tested locally with `helm template`. If you provide `>`, or `!=` as an operator you now get 
```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
refinery:
- rules.Samplers.testing.RulesBasedSampler.Rules.0.Conditions.0.Operator: String length must be greater than or equal to 1
```
Providing `>=` already caused an error.
> fix: Enforce operator string length

- charts/network-agent/Chart.yaml
- charts/network-agent/README.md
new honeycomb network agent [v0.0.20-alpha](https://github.com/honeycombio/honeycomb-network-agent/releases/tag/v0.0.20-alpha) published
- update appVersion to v0.0.20-alpha
- minor cleanup of readme
> maint: [network-agent] bump app version to v0.0.20-alpha

- charts/network-agent/CHANGELOG.md
Lack of a published helm chart for the Honeycomb Network Agent.
- Closes https://github.com/honeycombio/honeycomb-network-agent/issues/235
- Add changelog
- (no changes to version because this is the first one and it's already set to 0.0.1-alpha)
> rel: [network-agent] prepare first alpha release

- charts/network-agent/CHANGELOG.md
- charts/network-agent/Chart.yaml
Actual first release of the helm chart for network agent.
- update version to 0.0.1 instead of 0.0.1-alpha because the releasing process will not properly handle the alpha suffix in the tag.
tag and release works 😅
> rel: [network-agent] prep release 0.0.1

- charts/network-agent/Chart.yaml
- charts/network-agent/README.md
- charts/network-agent/templates/_helpers.tpl
- charts/network-agent/templates/cluster_role.yaml
- charts/network-agent/templates/cluster_role_binding.yaml
- charts/network-agent/templates/daemonset.yaml
- charts/network-agent/templates/secret.yaml
- charts/network-agent/templates/service_account.yaml
[Failed release](https://app.circleci.com/pipelines/github/honeycombio/helm-charts/819/workflows/01cf638e-3eef-4593-81f9-757850d900dc/jobs/431) because Chart name (hny-network-agent) didn't match directory name (network-agent). 
- We opted for network-agent for chart name because honeycomb and/or honeycombio will be included when using the chart. The dataset names and container/pod names are intentionally kept as hny-network-agent to make it more easily distinguishable since these are things the user will see in a running k8s cluster. 
- Added the environment variables necessary for the use of k8s downward API in the agent, which adds k8s metadata to events so the agent knows things about itself.
Events have all expected k8s metadata... and the release works 😅 😅
> maint: [network-agent] fix up network-agent chart

- charts/network-agent/values.yaml
Updates the example helm-chart to show how to configure additional HTTP headers to be extracted. 
- Implemented in https://github.com/honeycombio/honeycomb-network-agent/pull/277
- Update example values.yaml with commented out config that shows how to set additional HTTP headers to extract
The values.yaml show how to set additional headers to extract.
> maint: Adds HTTP headers example to values.yaml

- charts/network-agent/Chart.yaml
- charts/network-agent/values.yaml
Updates agent image version to [v0.0.22-alpha](https://github.com/honeycombio/honeycomb-network-agent/releases/tag/v0.0.22-alpha)
- Update chart's appVersion to v0.0.22-alpha
- Updates additional env var examples
> maint: Bump agent version to v0.0.22-alpha

- charts/network-agent/README.md
- charts/network-agent/templates/cluster_role.yaml
Documents the cluster privileges to run the agent.
- Closes https://github.com/honeycombio/honeycomb-network-agent/issues/167
- Upate list of resources to be more specific (nodes, pods & services) instead of `*` (all)
The Network Agent's read me includes details on cluster privileges.
> maint: Update and document Network Agent cluster privileges

- charts/network-agent/CHANGELOG.md
- charts/network-agent/Chart.yaml
Prepares the v0.0.3 release of the Honeycomb Network Agent chart.
- Adds changelog entry
- Update chart version to v0.0.3
New chart version is available.
> rel: Prepare v0.0.3 of Honeycomb Network Agent

- charts/network-agent/Chart.yaml
- charts/network-agent/README.md
- charts/network-agent/values.yaml
- update network agent appVersion to [0.0.24-alpha](https://github.com/honeycombio/honeycomb-network-agent/releases/tag/v0.0.24-alpha)
- update values.yaml for changes to environment variables now available with 24-alpha
- fix formatting in readme for privileges
> maint: [network-agent] update network agent to 0.0.24-alpha

- charts/refinery/templates/deployment.yaml
- charts/refinery/values.yaml
In the same fashion as podLabels. Add the ability to configure custom deployment labels for the refinery helm chart.
When running the following commands, the output should contain a `Deployment` resource for Refinery which contains the customer label `example.com/label: "true"`
```
echo 'deploymentLabels:                                                                                                                                                                                                                                                                                                                                                                                            
example.com/label: "true"' > values.yml
helm template refinery charts/refinery --namespace=test …
```
> feat: add deploymentLabels to refinery chart

- charts/network-agent/Chart.yaml
Update the Honeycomb Network Agent image version to latest. 
- Update app version in hny-network-agent chart to v0.0.25-alpha
The netwok agent chart uses the latest image version.
> maint: Bump hny network agent image to v0.0.25-alpha

- charts/network-agent/CHANGELOG.md
- charts/network-agent/Chart.yaml
Prepares the next release of the Honeycomb Network Agent helm chart. 
- Update chart version to 0.0.5
A new version of the network agent chart can be published.
> rel: Prepare v0.0.5 release of network agent

- charts/network-agent/templates/daemonset.yaml
- charts/network-agent/values.yaml
Adds support for custom pod annotations when deploying the network agent helm chart.
- Add `podAnnotations` empty set in network agent's default values yaml
- Apply `podAnnotations` to the daemonset resource
Custom pod annotations are applied to the network agent daemonset when set in the values yaml.
> feat: Add support for custom pod annotations to network agent

- charts/network-agent/CHANGELOG.md
- charts/network-agent/Chart.yaml
Prepares the v0.0.6 release of the Honeycomb network agent. 
- Update chart version to 0.0.6
The next release of the network agent can be published.
> rel: Prepare v0.0.6 release of network agent

- .circleci/config.yml
- .circleci/install_testing_tools.sh
- chart_schema.yaml
- charts/honeycomb/Chart.yaml
- charts/network-agent/Chart.yaml
- charts/refinery/Chart.yaml
- charts/refinery/values.yaml
- ct.yaml
- lintconf.yaml
Our charts dont have a linter, but that is required if we want to release on every commit (https://github.com/honeycombio/helm-charts/pull/309)
- Adds linting to the CI
- Fixes existing lint issues
CI
> maint: Add linting to CI

- .circleci/release.sh
Passing the ` --generate-release-notes` broke things.  The fix is to ensure the upload command has the latest commit. The chart-releaser action solves this like so: https://github.com/helm/chart-releaser-action/blob/6203d709ca237fb26b724837f2c53716f244ee8c/cr.sh#L318C38-L318C64
> maint: fix release note generation

- charts/refinery/Chart.yaml
This PR bumps the refinery app version to v2.2.0 and the chart version to v2.4.0
release a new chart for refinery v2.2.0
> maint: bump refinery to v2.2.0

- charts/network-agent/CHANGELOG.md
- charts/network-agent/Chart.yaml
Prepares the next version of the agent to be published.
- Updates chart version to 0.2.0
The next version of the chart can be published.
> rel(network-agent): Prepare chart version to v0.2.0

- charts/network-agent/Chart.yaml
Bumps the app image of the Network Agent to latest.
- Update app image version to v0.2.0-beta
- Update chart version to 0.3.0
New helm chart is published using latest agent image.
> maint(network-agent): Bump app version to 0.2.0-beta

- charts/refinery/Chart.yaml
Refinery v2.3.0 was released; this updates the chart to use this version.
> maint: Bump refinery version to 2.3.0

- charts/refinery/Chart.yaml
- charts/refinery/templates/deployment-redis.yaml
- charts/refinery/values.yaml
It should be possible to set redis resources from values.yaml
- Closes #331
Allow setting redis resources from values.
Configure resources in values.yaml under `redis.resources` and see that redis container resources are set accordingly.
> feat: Define redis resources

- charts/refinery/Chart.yaml
- charts/refinery/templates/_helpers.tpl
- charts/refinery/templates/configmap-config.yaml
- charts/refinery/templates/configmap-rules.yaml
- charts/refinery/templates/deployment-redis.yaml
- charts/refinery/templates/hpa.yaml
- charts/refinery/templates/ingress-beta.yaml
- charts/refinery/templates/secretprovider.yaml
- charts/refinery/templates/service-redis.yaml
- charts/refinery/values.yaml
It would be nice to be able to define custom labels on all resources managed by this chart.
- Closes #334
Allows defining a set of common labels to be applied to all resources.
It also enables managing labels and annotations on each resources independently.
E.g. set `extraLabels: <some labels>`  or `configMap.labels: <labels>` and verify epxected labels have been added to corresponding resources.
> feat: Configure refinery labels and annotations for each resources

- charts/refinery/Chart.yaml
- charts/refinery/templates/deployment-redis.yaml
- charts/refinery/templates/deployment.yaml
- charts/refinery/values.yaml
To make rolling update smoother, it is very common to add a sleep to containers preStop lifecycle to give Kubernetes some time to reconfigure the application's service endpoints.
- Closes #341
Allow configuring each container lifecycle.
Set values:
``` yaml
lifecycle: {}
preStop:
exec:
command:
- "sh"
- "-c"
- "sleep 10"
```
and check lifecycle has been configured as expected
> feat: Refinery lifecycle

- charts/honeycomb/Chart.yaml
Bumps Kubernetes Agent to 2.7.2.
- Closes #343 
- Update chart version to 1.8.3
- Update appVersion to 2.7.2
New Kubernetes Agent is available to install via helm chart.
> rel: Bump Kubernetes Agent to 2.7.2

- charts/network-agent/Chart.yaml
Bumps Network Agent to latest version.
- Update chart to 0.3.1
- Update appVersion to 0.2.1-beta
New Network agent version can be installed via helm chart.
> rel: Bump Network Agent to v0.2.1-beta

- charts/refinery/Chart.yaml
Bump refinery appVersion to 2.4 and bump chart version to 2.8.
> chore: bump refinery to 2.4

- charts/refinery/Chart.yaml
Bumps default refinery version to v2.5.0
- Closes https://github.com/honeycombio/helm-charts/issues/353
> maint: Bump refinery version to v2.5.0

- charts/refinery/Chart.yaml
- charts/refinery/ci/autoscale-values.yaml
- charts/refinery/ci/debug.yaml
- charts/refinery/ci/default-values.yaml
- charts/refinery/ci/ingress-values.yaml
- charts/refinery/ci/pdb-values.yaml
- charts/refinery/ci/rules-values.yaml
- charts/refinery/templates/NOTES.txt
- charts/refinery/templates/deployment-redis.yaml
- charts/refinery/templates/ingress-beta.yaml
- charts/refinery/templates/ingress-grpc.yaml
- charts/refinery/templates/statefulset-redis.yaml
- charts/refinery/values.schema.json
- charts/refinery/values.yaml
Prepares an "internal" release of the chart for us to test Refinery 3.0.0.  
> :warning: We do not recommend any customer use this version of the chart and we do not support it.
Changes:
- The commits from https://github.com/honeycombio/helm-charts/pull/278 (thanks @zenon-was-here!)
- Updated default refinery configuration
- Updated resource values
- A new Statefulset Redis deployment option
> rel: Prepare 3.0.0 pre-release

- .circleci/config.yml
- charts/refinery/Chart.yaml
For the 2.X version of the refinery helm chart, updates the default refinery version to be 2.5.1
- Closes https://github.com/honeycombio/helm-charts/issues/361
- bump appVersion to 2.5.1
- bump chart version to 2.9.1
- update CI to check against refinery-2.X-work-branch instead of main
Local testing
> rel(refinery): bump default refinery version to 2.5.1

- charts/refinery/Chart.yaml
- charts/refinery/templates/deployment.yaml
- charts/refinery/values.yaml
Allows users to configure readiness and liveness probes values
- allows setting `initialDelaySeconds`, `periodSeconds`, `timeoutSeconds`, and `failureThreshold` for `livenessProbe` and `readinessProbe`.
Tested locally
> feat(refinery): Allow configuring probes

- charts/refinery/Chart.yaml
Bumps the default refinery version to 2.5.2
- Closes https://github.com/honeycombio/helm-charts/issues/366
- Closes https://github.com/honeycombio/helm-charts/issues/365
- bump appVersion to 2.5.2
Local tests
> rel: bump default refinery version to 2.5.2

- .circleci/config.yml
Updates CI to use main again
removes the `--target-branch` flag from CI
> maint: remove refinery target branch

- charts/refinery/Chart.yaml
Prepares the v2.10.0 release of the Refinery chart based on Refinery v2.6.1.
- Update chart version to 2.10.0
- Update refinery version to 2.6.1
> rel: Bump Refinery to v2.6.1

- charts/refinery/Chart.yaml
- charts/refinery/templates/deployment.yaml
- charts/refinery/values.yaml
Refinery 2.7 has set up health check endpoints for readiness and liveness probes from k8s
- templating liveness and readiness probe in Refinery Deployment spec
local testing
> feat(refinery): enable templating for liveness and readiness probe

- charts/refinery/Chart.yaml
Helm chart release for Refinery 2.7.0
- remove internal suffix in chart version
- remove dev suffix in app version
> maint: prepare for Refinery chart v2.11.0 release

- charts/refinery/Chart.yaml
- charts/refinery/templates/deployment.yaml
- charts/refinery/values.yaml
Refinery 2.8 attempts to drain data to remaining peers on shutdown, and has a configurable ShutdownDelay field where it tries to process remaining work while shutting down. In k8s we need this config option to be inline with terminationGracePeriodSeconds to ensure k8s doesn't kill pods early.
it's the same change as #360 
- added terminationGracePeriodSeconds configuration option in values.yaml
- set ShutdownDelay to be terminationGracePeriodSeconds - 5 seconds by default. Users can override this value in their values.yaml
- publish a `-hnyinternal` tag for the change
Test localling using kind
> feat(refinery): Set ShutdownDelay based on terminationGracePeriodSeconds

- charts/refinery/Chart.yaml
- bump default refinery version to 2.8.2 in the chart
> feat(refinery): bump Refinery to 2.8.2

- .circleci/release.sh
The last release failed bc `cr package` depends on any chart dependencies being present. 
- runs `helm repo add` commands to add the required dependencies, similar to https://github.com/open-telemetry/opentelemetry-helm-charts/blob/43bf93cda3f16ba06c095d82c262f84886d90aae/.github/workflows/release.yaml#L27-L33
> fix: add chart deps during release

- charts/refinery/Chart.yaml
- charts/refinery/README.md
- charts/refinery/templates/deployment-redis.yaml
- charts/refinery/templates/deployment.yaml
- charts/refinery/values.yaml
- Closes #97 
Adds support for providing `topologySpreadConstraints` field. This will help us deploy refinery confirming to some topology constraints.
> feat(refinery): add support for topologySpreadConstraints

- charts/refinery/Chart.yaml
- charts/refinery/README.md
- charts/refinery/templates/NOTES.txt
- charts/refinery/templates/deployment-marker-job.yaml
- charts/refinery/values.yaml
It's helpful to know when a new version of Refinery has been deployed when viewing Refinery's telemetry data. This PR adds a deployment marker job in Refinery's chart. The job will create a honeycomb marker when a Refinery deployment happenes.
NOTE: This is a MVP version of this feature. There could be other improvements made down the line
- add a deployment-marker job. The job utilize helm hooks to only run after a `helm install` or `helm upgrade`
- introduce a new `REFINERY_HONEYCOMB_DEPLOY_MARKER_API_KEY` environment variable for sending deploy markers to honeycomb
Tested it locally
> feat(refinery): add deployment-marker support

- charts/refinery/Chart.yaml
- charts/refinery/README.md
Update the README to manage expectations around the new and experimental deploy marker behavior added in #400.
> docs(refinery): note experimental nature of deploy marker

- charts/observability-pipeline/Chart.yaml
- charts/observability-pipeline/templates/_helpters.tpl
- charts/observability-pipeline/templates/control-plane-configmap-otel.yaml
- charts/observability-pipeline/templates/control-plane-deployment.yaml
- charts/observability-pipeline/values.yaml
Adds ability to enable the control plane's instrumentation using otel's sdk configuration. When enabled, the chart will include and mount a configmap for configuring the exporting of the control plane's telemetry.
- add new configmap template
- add conditions to the control plane deployment to hook up config
- add default otel sdk config to push to the gateway collector that can be installed by this chart. This is the default instead of pushing to honeycomb because the otel configuraiton doesn't support env vars yet, so there isn't a way to pass in our honeycomb ingest key as a secret. Instead the default is to export the data to a collector which can properly manage the secret (and enhance with k8s attributes). 
Tested locally.
> feat(observability-pipeline): add control plane telemetry support

- charts/refinery/Chart.yaml
- charts/refinery/templates/deployment-marker-job.yaml
- Allow refinery pods to authenticate and pull honeymarker image.
- Add uniqueness for deployment marker job name so that concurrent deployment won't fail
- use the same `imagePullSecrets` from refinery for deployment marker
- add a randomly generated string to deployment marker job name
tested locally
> fix(refinery): deployment marker image pull secrets and job name uniqueness

- charts/observability-pipeline/Chart.yaml
- charts/observability-pipeline/values.yaml
Sets a default `REFINERY_HONEYCOMB_API_KEY` env var so that refinery can export telemetry using a default install.
- Add a default env var named REFINERY_HONEYCOMB_API_KEY that looks for the secret that users are instructed to create in the README
Local testing.
> feat(observability-pipeline): Add default refinery telemetry api key

- charts/observability-pipeline/Chart.yaml
- charts/observability-pipeline/templates/control-plane-deployment.yaml
I renamed the env var in control-place from configuration id to installation id https://github.com/honeycombio/straws-control-plane/pull/24
This PR is to match the helm-chart with the control place change
rename configuration id to installation id
> feat(observability-pipeline): rename configuration_id to installation_id

- charts/refinery/Chart.yaml
We just released refinery 2.9.2. Update the chart to use the latest refinery version
> maint(refinery): bump version to 2.15.3

- charts/observability-pipeline/Chart.yaml
- charts/observability-pipeline/ci/collectors-values.yaml
- charts/observability-pipeline/templates/NOTES.txt
- charts/observability-pipeline/templates/_helpters.tpl
- charts/observability-pipeline/templates/collector-configmap.yaml
- charts/observability-pipeline/templates/collector-deployment.yaml
- charts/observability-pipeline/templates/collector-service.yaml
- charts/observability-pipeline/templates/collector-serviceaccount.yaml
- charts/observability-pipeline/templates/control-plane-configmap-otel.yaml
- charts/observability-pipeline/templates/control-plane-deployment.yaml
- charts/observability-pipeline/templates/control-plane-service.yaml
- charts/observability-pipeline/templates/control-plane-serviceaccount.yaml
- charts/observability-pipeline/values.yaml
Allows the chart to install an opamp-managed collector (implemented via the opampsupervisor) that communicates with the control plane
- update test to not install an opamp-managed collector
- update control-plane helper templates to be namespaced with `controlPlane`
- add template files for installing an opampsupervisor deployment.
- update NOTES.txt to enforce specifying an image for the opampsupervisor
Tested locally in kind.
> feat(observability-pipeline): add opampsupervisor support

- charts/observability-pipeline/Chart.yaml
- charts/observability-pipeline/templates/collector-deployment.yaml
- charts/observability-pipeline/templates/control-plane-deployment.yaml
- charts/observability-pipeline/values.yaml
Add ability to set environment variables and volumes on the collector pods.
- add env support
- add volume support
- add volumeMount support
- add default env var
tested in sippycup
> feat(observability-pipeline): add support for environments and volumes

- charts/observability-pipeline/Chart.yaml
- charts/observability-pipeline/templates/control-plane-deployment.yaml
- charts/observability-pipeline/values.yaml
- adds support for using pvc to persist latest config in control plane
- add a new `persistentVolumnClaimName` in the `values.yaml` file to allow users to mount a volume
- pass in the mount path using `-config-cache-path` flag
> feat(observability-pipeline): use pvc for cacheing latest config

- charts/htp/Chart.yaml
- charts/htp/README.md
- charts/htp/values.yaml
- fixes an issue where the default username and password in the values.yaml were taking priority over any username/password set in the `config.secret`. This is an outcome of the bindplane chart: https://github.com/observIQ/bindplane-op-helm/blob/main/charts/bindplane/templates/bindplane.yaml#L135-L154
- remove default username and password values.
- update readme instructions
tested locally
> fix(htp): fix bug where username/password could not come from secret

- charts/observability-pipeline/Chart.lock
- charts/observability-pipeline/Chart.yaml
- charts/observability-pipeline/templates/_helpers.tpl
- charts/observability-pipeline/templates/beekeeper-deployment.yaml
- charts/observability-pipeline/templates/collector-deployment.yaml
Ensure that if config changes for beekeeper or the opampsupervisor that the deployments are rolled.
- Add template helpers to calculate checksum
- Add annotation to opampsupervisor and beekeeper deployments
- bump dep versions
- bump chart verison
local helm template
> feat(observability-pipeline): Add config checksum to annotations

- charts/observability-pipeline/Chart.yaml
- charts/observability-pipeline/values.yaml
Update the chart to use refinery opamp by default
- set default refinery image
- enable opamp
tested locally
> feat(observability-pipeline): use opamp by default

- charts/observability-pipeline/Chart.yaml
- charts/observability-pipeline/templates/_helpers.tpl
- charts/observability-pipeline/templates/beekeeper-deployment.yaml
- charts/observability-pipeline/values.yaml
https://app.asana.com/0/1208469935858869/1209598568289018
- adds support for new `TELEMETRY_METRICS_DATASET` env var to allow configuring how beekeeper injects the metrics dataset header for its clients.
- add new env var
- add ability to set collector's `service.name` value
Tested locally in kind
> feat(observability-pipeline): allow configuring metrics dataset

- README.md
The README in the `gh-pages` branch (which displays at https://honeycombio.github.io/helm-charts/) is out of date.
This makes it current with `main`.
No PR previews for GitHub Pages! So just have to compare READMEs.
https://github.com/honeycombio/helm-charts/blob/jessica.update-gh-pages/README.md
should look the same as
https://github.com/honeycombio/helm-charts/blob/main/README.md
And the links on both should go to the same places.
> Update gh-pages README to match main

- charts/observability-pipeline/Chart.yaml
- charts/observability-pipeline/README.md
- charts/observability-pipeline/templates/NOTES.txt
- charts/observability-pipeline/templates/beekeeper-deployment.yaml
- charts/observability-pipeline/templates/collector-deployment.yaml
- charts/observability-pipeline/values.yaml
To simplify the required chart config, move the team, pipelineInstallatinID, and management key to the root.
- move settings to root
- update templates
- update README
Local templating
> maint(observability-pipeline): move required fields to root

- charts/observability-pipeline/Chart.yaml
- charts/observability-pipeline/templates/_helpers.tpl
This adds the service.namespace field to the opampsupervisor configuration.
> feat: add service.namespace to supervisor config

- charts/observability-pipeline/Chart.yaml
- charts/observability-pipeline/templates/_helpers.tpl
- charts/observability-pipeline/templates/beekeeper-deployment.yaml
- charts/observability-pipeline/values.yaml
fixes an issue where the primary collector service name was not used for its metrics data
helm template
> fix(observability-pipeline): reuse primaryCollector service name

- charts/htp/Chart.lock
Fix the broken bindplane release deploy
Update bindplane chart.lock to match chart version
Circle job passes
> fix(bindplane): update bindplane chart.lock version

- charts/observability-pipeline/Chart.yaml
- charts/observability-pipeline/README.md
- charts/observability-pipeline/templates/NOTES.txt
- charts/observability-pipeline/templates/beekeeper-deployment.yaml
- charts/observability-pipeline/values.yaml
Remove unused team variable now beekeeper doesn't [use it anymore](https://github.com/honeycombio/beekeeper/pull/87).
- remove team variable, usage in beekeeper values and validation in notes.txt
> maint: Remove unused team variable

- charts/refinery/Chart.yaml
- charts/refinery/templates/_helpers.tpl
- charts/refinery/values.yaml
Right now eu customer need to manually set a couple refinery configuration endpoints to point to eu honeycomb instead of prod. That is kind of annoying. This PR allows the chart to automatically set those fields based on a flag.
- add new `region` setting that will automatically configure refinery's endpoints based on the value
- Add comments
tested locally using `helm template`
> feat(refinery): Make it easy to set eu1 urls

- charts/refinery/Chart.yaml
- charts/refinery/templates/_helpers.tpl
when using the region feature in the refinery chart as a subchart the parent chart can only pass a value into the subchart via `global`.
- updates the chart to support `global.region`, with `region` taking precedence if it is set.
> feat(refinery): allow setting region from global

- charts/observability-pipeline/Chart.lock
- charts/observability-pipeline/Chart.yaml
- charts/observability-pipeline/templates/NOTES.txt
- charts/observability-pipeline/templates/_helpers.tpl
- charts/observability-pipeline/templates/beekeeper-deployment.yaml
- charts/observability-pipeline/templates/primary-collector-configmap.yaml
- charts/observability-pipeline/templates/primary-collector-deployment.yaml
- charts/observability-pipeline/templates/primary-collector-service.yaml
- charts/observability-pipeline/templates/primary-collector-serviceaccount.yaml
- charts/observability-pipeline/values.yaml
There are a lot of urls to configure if you're not going to prod-us1. This PR adds a new `global.region` option that our EU customers can use to easily swap all the urls to point to the appropriate `-eu1` version instead of the US version.
- add `global.region` setting in values.yaml
- update refinery chart to be able to use its `region` feature
- update beekeeper.endpoint to factor in region
- update beekeeper TELEMETRY_ENDPOINT to factor in region
- update primaryCollector opampsupervisor telemetry to factor in region
- fix some incorrectly named templates
> feat(observability-pipeline): allow setting region

- charts/observability-pipeline/Chart.yaml
- charts/observability-pipeline/templates/_helpers.tpl
- charts/observability-pipeline/values.yaml
The chart is currently defaulting the endpoint to `"ws://<release name>-beekeeper:4320/v1/opamp"`, but the default service name for beekeeper is `<release name>-observability-pipeline-beekeeper`.
- fix the default opamp endpoint for refinery to point to the default beekeeper service
tested locally in kind
> fix(observability-pipeline): fix default refinery opamp endpoint

- charts/observability-pipeline/Chart.yaml
- charts/observability-pipeline/templates/NOTES.txt
Right now you can install the chart pointing to production-us unless you explicitly set it in beekeeper.endpoint. That was an unintentional side effect of https://github.com/honeycombio/helm-charts/pull/462. Turns out the check I added isn't necessary bc an unset value means `production-us` and I had forgotten to update NOTES.txt
- Closes https://github.com/honeycombio/helm-charts/pull/462
- remove unneeded check.
helm template
> fix(observability-pipeline): fix bug preventing default install

- charts/observability-pipeline/Chart.yaml
- charts/observability-pipeline/values.schema.json
- charts/observability-pipeline/values.yaml
Related to https://github.com/honeycombio/pipeline-team/issues/239
Add a json schema to help enforce keys in the values.yaml. This ensures users don't mistype something and get confused. It will also help with changing values in later versions if needed.
Tested locally with `helm template`.
> feat(observability-pipeline): add json schema for the chart

- charts/refinery/Chart.yaml
update the chart to use the latest Refinery release 2.9.5
> maint(refinery): update chart to use 2.9.5

- charts/observability-pipeline/Chart.yaml
- charts/observability-pipeline/templates/_helpers.tpl
- charts/observability-pipeline/templates/beekeeper-deployment.yaml
- charts/observability-pipeline/templates/primary-collector-agent-configmap.yaml
- charts/observability-pipeline/templates/primary-collector-deployment.yaml
- charts/observability-pipeline/values.yaml
closes https://github.com/honeycombio/pipeline-team/issues/255
Switch the primary collector's telemetry settings to a local file from helm instead of from Beekeeper. This brings it in line with beekeeper, refinery and the opampsupervisor. It also ensures the collector can emit telemetry even if it doesn't get the chance to talk to beekeeper
local testing and templating
> feat(observability-pipeline): switch collector telemetry config to file

- charts/observability-pipeline/Chart.yaml
- charts/observability-pipeline/templates/_helpers.tpl
- charts/observability-pipeline/values.yaml
Beekeeper telemetry endpoint cannot currently be easily set to a non-prod url.
- update beekeeper to use `.Values.beekeeper.endpoint` for otel sdk endpoint if it is set.
templating and installing in sippycup
> fix(observability-pipeline): allow beekeeper telemetry endpoint to set to non-prod

- charts/observability-pipeline/Chart.yaml
- charts/observability-pipeline/values.yaml
I broke refinery telemetry exporting with https://github.com/honeycombio/helm-charts/pull/477
- add back the default env var for exporting refinery telemetry
- add comments
Tested by installing this version of the chart in sippycup
> fix(observability-pipeline): add back refinery telemetry key

- charts/observability-pipeline/Chart.yaml
- charts/observability-pipeline/templates/_helpers.tpl
- charts/observability-pipeline/templates/primary-collector-deployment.yaml
- charts/observability-pipeline/values.schema.json
- charts/observability-pipeline/values.yaml
- related to https://github.com/honeycombio/pipeline-team/issues/383
- update chart version
- update json schema with new default env var
- add new default env var to primary collector that provides access to installed refinery service name
> feat(observability-pipeline): set env var for refinery service name

- charts/observability-pipeline/Chart.yaml
- charts/observability-pipeline/templates/_helpers.tpl
Fixes the same issue from https://github.com/honeycombio/helm-charts/pull/467  that broke the url when the chart name was used in the release name, this time for the primary collector.
- Related to https://github.com/honeycombio/pipeline-team/issues/390
- use the proper beekeeper service name for the opamp server host.
> fix(observability-pipeline): fix beekeeper url for opampsupervisor

- charts/refinery/Chart.yaml
- charts/refinery/templates/_helpers.tpl
- charts/refinery/values.schema.json
- charts/refinery/values.yaml
- tests/refinery/rendered/rendered-customEndpoint.yaml
- tests/refinery/rendered/rendered-eu.yaml
- tests/refinery/rendered/rendered-eu1.yaml
- tests/refinery/rendered/rendered-global-customEndpoint.yaml
- tests/refinery/rendered/rendered-global-region-eu1.yaml
- tests/refinery/rendered/rendered-global-region-us1.yaml
- tests/refinery/rendered/rendered-unset-region.yaml
- tests/refinery/rendered/rendered-us1.yaml
- tests/refinery/tests/customEndpoint.yaml
- tests/refinery/tests/eu.yaml
- tests/refinery/tests/eu1.yaml
- tests/refinery/tests/global-customEndpoint.yaml
- tests/refinery/tests/global-region-eu1.yaml
- tests/refinery/tests/global-region-us1.yaml
- tests/refinery/tests/unset-region.yaml
- tests/refinery/tests/us1.yaml
The charts should remain consistent with naming of environment in honeycomb, in that it should allow eu1, us1, etc. without `production-`
- Related to https://github.com/honeycombio/pipeline-team/issues/398
updated the schema and _helper to take into account new regions
The tests cover all the rendering issues
> feat(refinery): allowing us1 and eu1 as regions for refinery, including from `global`

- charts/refinery/Chart.yaml
- charts/refinery/templates/deployment.yaml
- charts/refinery/values.yaml
Allow templating environment variables
- Related to https://github.com/honeycombio/pipeline-team/issues/411
- update chart to run `.Values.environment` through `tpl`. This enables users to set environment variables using helm templates. We'll use this in the observability-pipeline chart to set otel resource attributes using values from the values.yaml.
local templating.
> feat(refinery): allow templating env vars

- charts/observability-pipeline/Chart.yaml
- charts/observability-pipeline/README.md
- charts/observability-pipeline/templates/NOTES.txt
- charts/observability-pipeline/templates/beekeeper-deployment.yaml
- charts/observability-pipeline/templates/primary-collector-deployment.yaml
- charts/observability-pipeline/values.schema.json
- charts/observability-pipeline/values.yaml
- tests/observability-pipeline/base-values.yaml
Naming consistency for the helm values
- Closes https://github.com/honeycombio/pipeline-team/issues/416
renamed `pipelineInstallationId` to `global.pipeline.id`
Rendering shows no changes when the variable is moved in the values file.
> feat(observability-pipeline): renamed the pipelineInstallationId variable

- charts/observability-pipeline/Chart.yaml
- charts/observability-pipeline/templates/_helpers.tpl
- charts/observability-pipeline/values.schema.json
- charts/observability-pipeline/values.yaml
- tests/observability-pipeline/rendered/rendered-customEndpoint.yaml
- tests/observability-pipeline/rendered/rendered-eu1.yaml
- tests/observability-pipeline/rendered/rendered-unset-region.yaml
During testing we found that if the primary-collector has a lot of connections it takes longer to shutdown and startup during a rollout. The hard-coded 10s was causing rollouts to look like they failed.
- update default value to 30s
- allow configuring value
> feat(observability-pipeline): allow specifying config_apply_timeout

- charts/observability-pipeline/Chart.yaml
- charts/observability-pipeline/templates/_helpers.tpl
Enable the configuration to enable sending logs from the supervised collector through the supervisor.
> feat(observability-pipeline): enable passthrough logs

- charts/htp-builder/Chart.yaml
- charts/htp-builder/README.md
- charts/htp-builder/templates/NOTES.txt
- charts/htp-builder/templates/beekeeper-deployment.yaml
- charts/htp-builder/values.schema.json
- charts/htp-builder/values.yaml
- tests/htp-builder/base-values.yaml
- tests/htp-builder/rendered/rendered-customEndpoint.yaml
- tests/htp-builder/rendered/rendered-eu1.yaml
- tests/htp-builder/rendered/rendered-unset-region.yaml
- Closes https://github.com/honeycombio/pipeline-team/issues/417
- moves mangement api key management into its own section
- add comments
- update NOTES.txt checks
- update json schema
- remove unneeded default env var
- update beekeeper template to use new section
test rendering
> fix: move management api key into section

- charts/htp-builder/Chart.yaml
- charts/htp-builder/templates/beekeeper-deployment.yaml
- charts/htp-builder/templates/primary-collector-deployment.yaml
- charts/htp-builder/templates/refinery-deployment.yaml
- tests/htp-builder/rendered/rendered-customEndpoint.yaml
- tests/htp-builder/rendered/rendered-eu1.yaml
- tests/htp-builder/rendered/rendered-unset-region.yaml
Updates pipeline id resource attribute name and updates refinery to use k8s env vars and otel resource attributes.
- rename from attribute from `pipelineInstallationID` to `pipeline.id`
- update refinery to use otel resource attributes and set `pipeline.id` and common k8s attributes.
sippycup
> feat(htp-builder): include pipeline.id resource attribute wherever possible

- charts/htp-builder/Chart.yaml
- charts/htp-builder/templates/NOTES.txt
- charts/htp-builder/templates/primary-collector-deployment.yaml
- charts/htp-builder/templates/refinery-deployment.yaml
- charts/htp-builder/values.schema.json
- charts/htp-builder/values.yaml
- tests/htp-builder/rendered/rendered-customEndpoint.yaml
- tests/htp-builder/rendered/rendered-eu1.yaml
- tests/htp-builder/rendered/rendered-unset-region.yaml
Makes it easier for the user to configure the pipeline's ingest key, which is needed in both collector and refinery.
I went with a singular approach because at the moment the pipeline is pretty tied to a single environment. In the future when we're ready to better support more ingest keys in a pipeline (assuming we do that) we can add additional sections either at the root or nested in `ingestKey`. For now, users can add additional ingest keys to the primary collector via `primaryCollector.extraEnvs`.
- Closes https://github.com/honeycombio/pipeline-team/issues/419
- add new section to values.yaml
- update refinery and primary collector deployments with env var. For now beekeeper doesn't need this key.
tests and local templating
> feat(htp-builder): simpler key configuration

- charts/htp-builder/Chart.yaml
- charts/htp-builder/templates/_helpers.tpl
In https://github.com/honeycombio/supervised-collector/pull/17 I made a breaking change to updated the executable name to be honeycomb-specific. The helm chart needs to reflect this.
Update executable name to match supervised-collector
sippycup
> fix(htp-builder): update executable to new name

- charts/refinery/Chart.yaml
Update default Refinery app version to the latest 2.9.6 release
tested locally
> feat: update default refinery app version to 2.9.6

- charts/refinery/Chart.yaml
- tests/refinery/rendered/rendered-customEndpoint.yaml
- tests/refinery/rendered/rendered-eu.yaml
- tests/refinery/rendered/rendered-eu1.yaml
- tests/refinery/rendered/rendered-global-customEndpoint.yaml
- tests/refinery/rendered/rendered-global-region-eu1.yaml
- tests/refinery/rendered/rendered-global-region-us1.yaml
- tests/refinery/rendered/rendered-unset-region.yaml
- tests/refinery/rendered/rendered-us1.yaml
- Closes https://github.com/honeycombio/helm-charts/issues/524
bump appVersion to v2.9.7
tests
> maint(refinery): bump default refinery version to v2.9.7

- charts/htp-builder/Chart.yaml
- charts/htp-builder/templates/refinery-deployment.yaml
- tests/htp-builder/rendered/rendered-customEndpoint.yaml
- tests/htp-builder/rendered/rendered-eu1.yaml
- tests/htp-builder/rendered/rendered-unset-region.yaml
Fixes a bug where the `REFINERY_HONEYCOMB_LOGGER_ADDITIONAL_ATTRIBUTES` env var was not properly configured
- update env var name
- update env var value to use `:`, which is what refinery requires.
installed in test cluster.
> fix(htp-builder): fix broken REFINERY_HONEYCOMB_LOGGER_ADDITIONAL_ATTRIBUTES env var

- charts/htp-builder/Chart.yaml
- charts/htp-builder/values.schema.json
Adds `global` to the json schema so that the field is usable when subcharting.
> feat(htp-builder): add global to values schema

- charts/refinery/Chart.yaml
- charts/refinery/README.md
Use the correct doc link for migration doc in README.md
> fix(refinery): use correct link for migration doc in README

- charts/htp-bindplane/Chart.lock
- charts/htp-bindplane/Chart.yaml
- charts/htp/Chart.lock
- charts/htp/Chart.yaml
This is a retroactive release to support v1.29.2
> maint(htp-bindplane): update htp and htp-bindplane charts to 1.29.2

- charts/htp-bindplane/Chart.lock
- charts/htp-bindplane/Chart.yaml
- charts/htp/Chart.lock
- charts/htp/Chart.yaml
This is a retroactive release to support 1.31.0
> maint(htp-bindplane): update htp and htp-bindplane charts to 1.31.0
